### ISSUE TITLE
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.

### ISSUE THREAD

**Issue by WaffleGM** [p0dalirius/owabrute#2]
Hello, I'm a novice hacker, and I am attempting to recover the email address of a deceased family member whose password is unknown. Upon attempting to use this tool to brute force a password, I received this error:

[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.

I have the domain set to 'outlook.com', my username directory, 'user.txt' containing various arrangements of the email address (not including the domain and @), and the password directory as a simple 'rockyou.txt' wordlist for testing.

I am using a virtualized Ubuntu through WSL, and everything else I try seems to be working fine. I assume I just entered the wrong domain or something, but am not sure what else to put. Please let me know if you can help me out, and thank you for developing this tool!

**Comment by p0dalirius** [comment]
Hi,

This tool was meant to brute force Outlook Web App deployed by companies on their domains like this interface:

![image](https://github.com/user-attachments/assets/709e9af7-fdb6-4d7b-8d65-d8fcfe0055b8)

It is meant to test the security of such pages. It cannot be used to bruteforce outlook.com 

Best regards,
